version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfiles/dev/Dockerfile
    command: npm start
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
