version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfiles/dev/Dockerfile
    volumes:
      - ./app/:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
